include::ROOT:partial$variables.adoc[]

= `2021.9.5`

*Released on*: TBD

*Contributors*:
//Katrin Yordanova (https://github.com/katrinDY[GH]),
//Vivek Patel (https://github.com/vicpatel[GH]),
//Jože Fortun (https://github.com/fajfa[GH]),
Denis Arh (https://github.com/darh[GH]),
Tomaž Jerman (https://github.com/tjerman[GH]).

.[#2021_9_5-added]#<<2021_9_5-added,Added:>>#
* Role security (forbidden, permitted, forced) on external authentication providers ({SERVER_COMMIT_BASE}91eb88d2[`91eb88d2`]).
* Workflow functions for attachment managemnt ({SERVER_COMMIT_BASE}8a8c7685[`8a8c7685`]).
//
//

.[#2021_9_5-fixed]#<<2021_9_5-fixed,Fixed:>>#
* Translatable content (modules, names, pages, namespaces) is now sent with current language ({WEBAPP_COMPOSE_COMMIT_BASE}5bd3bd37[`5bd3bd37`]).
* Improve slow performance in some casses with wf-loops by increesing workflow session state flushing from 10 to 1000 ({SERVER_COMMIT_BASE}486a5752[`486a5752`]).
//
//

.[#2021_9_5-changed]#<<2021_9_5-changed,Changed:>>#
//* Admin role membership management ({WEBAPP_ADMIN_COMMIT_BASE}2df2f48[`2df2f48`]).

//
//

.[#2021_9_5-removed]#<<2021_9_5-removed,Removed:>>#
* Removed the unused `COUNTD` metric aggregation function ({WEBAPP_JS_COMMIT_BASE}29e8ab2a[`29e8ab2a`], {LOCALE_COMMIT_BASE}58a0a3b7[`58a0a3b7`], {WEBAPP_COMPOSE_COMMIT_BASE}commit/4633b238[`commit/4633b238`])

//
//

.[#2021_9_5-security]#<<2021_9_5-security,Security:>>#
//* Update Bluemonday & net packages ({SERVER_COMMIT_BASE}73c0b312[`73c0b312`]).
