include::ROOT:partial$variables.adoc[]

= `2021.9.6`

*Released on*: TBD

*Contributors*:
Katrin Yordanova (https://github.com/katrinDY[GH]),
Vivek Patel (https://github.com/vicpatel[GH]),
//Jože Fortun (https://github.com/fajfa[GH]),
Denis Arh (https://github.com/darh[GH]),
Tomaž Jerman (https://github.com/tjerman[GH]).
Peter Grlica (https://github.com/petergrlica[GH]).

.[#2021_9_6-added]#<<2021_9_6-added,Added:>>#
* Support for additional arguments when invoking Corredor script via API ({SERVER_COMMIT_BASE}91eb88d2[`91eb88d2`]).
* Support resource translation for select field texts ({SERVER_COMMIT_BASE}c72902a8[`c72902a8`]).
* SAML signed requests support ({SERVER_COMMIT_BASE}5e4486c7[`5e4486c7`], {WEBAPP_ADMIN_COMMIT_BASE}7ec02f6e[`7ec02f6e`]).
* Find and has expr functions ({SERVER_COMMIT_BASE}86deaea9[`86deaea9`]).
* Added checkbox which can hide import button separately from save button in Record list ({WEBAPP_COMPOSE_COMMIT_BASE}cd982a8[`cd982a8`], {WEBAPP_JS_COMMIT_BASE}9c85d0b[`9c85d0b`], {LOCALE_COMMIT_BASE}874e0b2[`874e0b2`]).
* Support for SAML HTTP binding ({SERVER_COMMIT_BASE}717cae5c0b[`717cae5c0b`], {WEBAPP_ADMIN_COMMIT_BASE}5cf0597b40[`5cf0597b40`])
* Support version in DB_DSN for development mode ({SERVER_COMMIT_BASE}c3516dd[`c3516dd`]).
* Sort an array expr function ({SERVER_COMMIT_BASE}be6b572[`be6b572`]).
* Persist column order after save in ColumnPicker ({WEBAPP_COMPOSE_COMMIT_BASE}9659d9f[`9659d9f`], {WEBAPP_JS_COMMIT_BASE}2b7c949[`2b7c949`], {LOCALE_COMMIT_BASE}b53bc6b[`b53bc6b`]).
* Record list filter multi value support ({WEBAPP_COMPOSE_COMMIT_BASE}d0213cb[`d0213cb`])
* RTL support

//
//

.[#2021_9_6-fixed]#<<2021_9_6-fixed,Fixed:>>#
* Refactored workflow execution and fixed runner/invoker logic ({SERVER_COMMIT_BASE}92224360[`92224360`]).
* Fixed improper attachment upload permission checks due to partial request parameters (https://github.com/cortezaproject/corteza-server/pull/309[#309], https://github.com/cortezaproject/corteza-webapp-compose/pull/346[#346]).
* Fixed improper QL argument transformations based on the used database (https://github.com/cortezaproject/corteza-server/pull/308[#308]).
* Fix broken docker container healtcheck on Corredor server ({SERVER_CORREDOR_COMMIT_BASE}dce30ba[`dce30ba`]).
* Changed federation locales ({WEBAPP_COMPOSE_COMMIT_BASE}91094e44[`91094e44`]).
* Refactored minio store and fixed invalid bucket name issue ({SERVER_COMMIT_BASE}23a2446[`23a2446`]).
* Fixed scrolling when only one pageBlock is added ({WEBAPP_COMPOSE_COMMIT_BASE}88f3e72[`88f3e72`]).
// couldn't find the link for corteza docs
* Fixed scrolling in left navigation for corteza-docs ({https://github.com/cortezaproject/corteza-docs/commit/5176de36ae589d5d63618cfe1588a11bec038969).
* Fixed translations on password reset ({SERVER_COMMIT_BASE}87f08d8[`87f08d8`]).
* RBAC rules & workflows are now reloaded after namespace import ({SERVER_COMMIT_BASE}ff6cadc0[`ff6cadc0`]).
* Handling empty strings (resource-translations) ({SERVER_COMMIT_BASE}4b264798[`4b264798`], {WEBAPP_COMPOSE_COMMIT_BASE}043588f1[`043588f1`]).
* Fixed external OIDC for corteza flow ({SERVER_COMMIT_BASE}398242b[`398242b`]).
* Fixed percentage calculation for all types of charts ({WEBAPP_JS_COMMIT_BASE}2b7c949[`2b7c949`]).
* Renamed FieldsPicker's props to match the component's context ({WEBAPP_VUE_COMMIT_BASE}fa80ade[`fa80ade`], {WEBAPP_COMPOSE_COMMIT_BASE}485187e[`485187e`]).
* Fixed namespace importing -- additional request validation ({SERVER_COMMIT_BASE}ca178714b[`ca178714b`]), improve internal resource identification ({SERVER_COMMIT_BASE}00dd86fb9[`00dd86fb9`], {SERVER_COMMIT_BASE}d247ec678[`d247ec678`], and {SERVER_COMMIT_BASE}8be8be96d[`8be8be96d`]).
* Fixed improper API request content parsing when `Content-Type` defines character set ({SERVER_COMMIT_BASE}d0154cc1b[`d0154cc1b`]).
* Fixed improper error handling for the upload component ({WEBAPP_COMPOSE_COMMIT_BASE}a0a1ac0[`a0a1ac0`]).
* Fix role-security setting for external providers ({WEBAPP_COMPOSE_COMMIT_BASE}05a40ca[`05a40ca`]).
* Fix issue with removal of OIDC provider ({WEBAPP_COMPOSE_COMMIT_BASE}c078808[`c078808`]).
* Fix queue name matching on workflow onMessage event ({SERVER_COMMIT_BASE}79d8a842[`79d8a842`])
* Fixed calendar not showing events that span multiple months properly ({WEBAPP_JS_COMMIT_BASE}4d2f824[`4d2f824`])
* Fixed record list filter for number and id fields ({WEBAPP_COMPOSE_COMMIT_BASE}3b421a1[`3b421a1`])
* Fixed namespace selector overflowing sidebar ({WEBAPP_COMPOSE_COMMIT_BASE}b9aa41e[`b9aa41e`])
* Fix metric page block field selector options ({WEBAPP_COMPOSE_COMMIT_BASE}cb69c80[`cb69c80`])
* Fix chart canvas not existing ({WEBAPP_COMPOSE_COMMIT_BASE}1b965f8[`1b965f8`])
* Record list empty text not centered ({WEBAPP_COMPOSE_COMMIT_BASE}f467e0f[`f467e0f`])
* Inline record editor delete not checking permissions ({WEBAPP_COMPOSE_COMMIT_BASE}f74d398[`f74d398`])
* Show processing when deleting records in record list ({WEBAPP_COMPOSE_COMMIT_BASE}6d47c1b[`6d47c1b`])
* Fix reminders not displaying properly ({WEBAPP_COMPOSE_COMMIT_BASE}94247f0[`94247f0`])
* Fix members fetching for closed roles ({WEBAPP_ADMIN_COMMIT_BASE}88955eb[`88955eb`])

//
//

.[#2021_9_6-changed]#<<2021_9_6-changed,Changed:>>#
* Make default value not required for multi fields ({WEBAPP_COMPOSE_COMMIT_BASE}aae3f6f[`aae3f6f`])
* Prefill inline record editor related values ({WEBAPP_COMPOSE_COMMIT_BASE}c457679[`c457679`])
* Disable page deletion if it has sub-pages ({WEBAPP_COMPOSE_COMMIT_BASE}67c3b2c[`67c3b2c`])
* Updated links in README.md and CONTRIBUTING.md files in all repos
//* placeholder-placeholder-placeholder ({SERVER_COMMIT_BASE}xxxxxxx[`xxxxxxx`]).

//
//

//.[#2021_9_6-security]#<<2021_9_6-security,Security:>>#
//* placeholder-placeholder-placeholder ({SERVER_COMMIT_BASE}xxxxxxx[`xxxxxxx`]).
