include::ROOT:partial$variables.adoc[]

= `2021.9.6`

*Released on*: TBD

*Contributors*:
Katrin Yordanova (https://github.com/katrinDY[GH]),
Vivek Patel (https://github.com/vicpatel[GH]),
//Jože Fortun (https://github.com/fajfa[GH]),
Denis Arh (https://github.com/darh[GH]),
Tomaž Jerman (https://github.com/tjerman[GH]).
Peter Grlica (https://github.com/petergrlica[GH]).

.[#2021_9_6-added]#<<2021_9_6-added,Added:>>#
* Support for additional arguments when invoking Corredor script via API ({SERVER_COMMIT_BASE}91eb88d2[`91eb88d2`]).
* Support resource translation for select field texts ({SERVER_COMMIT_BASE}c72902a8[`c72902a8`]).
* SAML signed requests support ({SERVER_COMMIT_BASE}5e4486c7[`5e4486c7`], {WEBAPP_ADMIN_COMMIT_BASE}7ec02f6e[`7ec02f6e`]).
* Find and has expr functions ({SERVER_COMMIT_BASE}86deaea9[`86deaea9`]).
* Added checkbox which can hide import button separately from save button in Record list {WEBAPP_COMPOSE_COMMIT_BASE}cd982a8[`cd982a8`], {WEBAPP_JS_COMMIT_BASE}9c85d0b[`9c85d0b`], {LOCALE_COMMIT_BASE}874e0b2[`874e0b2`].
//
//

.[#2021_9_6-fixed]#<<2021_9_6-fixed,Fixed:>>#
* Refactored workflow execution and fixed runner/invoker logic ({SERVER_COMMIT_BASE}92224360[`92224360`]).
* Fixed improper attachment upload permission checks due to partial request parameters (https://github.com/cortezaproject/corteza-server/pull/309[#309], https://github.com/cortezaproject/corteza-webapp-compose/pull/346[#346]).
* Fixed improper QL argument transformations based on the used database (https://github.com/cortezaproject/corteza-server/pull/308[#308]).
* Fix broken docker container healtcheck on Corredor server ({SERVER_CORREDOR_COMMIT_BASE}dce30ba[`dce30ba`]).
* Changed federation locales ({WEBAPP_COMPOSE_COMMIT_BASE}91094e44[`91094e44`]).
* Refactored minio store and fixed invalid bucket name issue ({SERVER_COMMIT_BASE}23a2446[`23a2446`]).
* Fixed scrolling when only one pageBlock is added ({WEBAPP_COMPOSE_COMMIT_BASE}88f3e72[`88f3e72`]).
// couldn't find the link for corteza docs
* Fixed scrolling in left navigation for corteza-docs ({https://github.com/cortezaproject/corteza-docs/commit/5176de36ae589d5d63618cfe1588a11bec038969).
* Fixed translations on password reset ({SERVER_COMMIT_BASE}87f08d8[`87f08d8`]).

//
//

//.[#2021_9_6-changed]#<<2021_9_6-changed,Changed:>>#
//* placeholder-placeholder-placeholder ({SERVER_COMMIT_BASE}xxxxxxx[`xxxxxxx`]).

//
//

//.[#2021_9_6-security]#<<2021_9_6-security,Security:>>#
//* placeholder-placeholder-placeholder ({SERVER_COMMIT_BASE}xxxxxxx[`xxxxxxx`]).
