include::ROOT:partial$variables.adoc[]

:PATCH_V: 2021_9_8

= `2021.9.8`

*Released on*: `YYYY-MM-DD`

.[#{PATCH_V}-added]#<<{PATCH_V}-added,Added:>>#
// Use list for *new features*

.[#{PATCH_V}-changed]#<<{PATCH_V}-changed,Changed:>>#
// Use list for *additions to the existing features*

.[#{PATCH_V}-deprecated]#<<{PATCH_V}-deprecated,Deprecated:>>#
// Use list for *things that should not be used but are still there*

.[#{PATCH_V}-removed]#<<{PATCH_V}-removed,Removed:>>#
// Use list for *removed things*

.[#{PATCH_V}-fixed]#<<{PATCH_V}-fixed,Fixed:>>#
// Use list for *fixes to existing features*
// If the modification changes the original flow of the feature, mention it under changes as well
. Fixed `count` expression function to properly handle the no argument case when typed values are being used (usually when invoked via workflow expressions) ({SERVER_COMMIT_BASE}5d7d3aa3[`5d7d3aa3`]).
. Fixed improper page blockID assignment on page create ({SERVER_COMMIT_BASE}95065f8e7[`95065f8e7`]).
. Fixed improper page blockID assignment on page create ({SERVER_COMMIT_BASE}95065f8e7[`95065f8e7`]).
. Fixed role management on external auth providers ({WEBAPP_COMPOSE_COMMIT_BASE}[d679a59[`d679a59`]).
. Append custom args when executing corredor scripts via Compose REST handlers ({SERVER_COMMIT_BASE}[2741e3577[`2741e3577`]).
. Better handling of unresolved (type any) values ({SERVER_COMMIT_BASE}[5ff68c414[`5ff68c414`]).

.[#{PATCH_V}-security]#<<{PATCH_V}-security,Security:>>#
// Use list for *security related changes*
. Strengthen reset-password flow with rate limiting and invalidation of existing tokens({WEBAPP_WORKFLOW_COMMIT_BASE}d2d0245d5[`d2d0245d5`]).
. Improve attachment validation on size and type for compose uploads ({SERVER_COMMIT_BASE}6f19f00b2[`6f19f00b2`]).
. Sanitize back-link on logout page (XSS) ({SERVER_COMMIT_BASE}8c0a62284[`8c0a62284`]).
. Refactor delete all session of user from auth page ({SERVER_COMMIT_BASE}23a8b757ee[`23a8b757ee`]).
