include::ROOT:partial$variables.adoc[]

= Unit tests

include::partial$testing/unit-test-tldr.adoc[]

{PRODUCT_NAME} uses the https://mochajs.org/[Mocha] test runner with the https://www.chaijs.com/[Chai] assertion library.

Unit tests reside inside the directory, next to the file, the testee is implemented in.
To exemplify; to test the `compose.Module` class inside the `src/compose/types/module.ts` file, you would define the test cases in the `src/compose/types/module.test.ts`

A *test case* is a complete flow defined by the specific function(s) usually only defined based on the input.
To exemplify; for a successful integer addition one test case would check if the addition of two numbers is correct and another one to check if overflow/underflow is handled correctly.

[NOTE]
====
Unit tests should focus on smaller part such as specific functions.
They can, however implicitly test supporting functions -- the functions called by the testee.
====

* Meta stuff
** how do I define the scope a unit test should cover?
** what wording should I use for test case names?
* Testing stuff
** Generic tests (envoy, workflow execution, ...)
*** How should the setup procedure look like?
*** How should a test case look like
*** What all can I use to assert my tests; the assert package

== Base test template

Use the following code snippet as a starting point when defining your tests

[source,ts]
----
import { expect } from 'chai'
// ...
// other imports here
// ...

describe(__filename, () => {
  describe('a flow with smaller sub-flows', () => {
    it('flow name', () => {
      // Evaluation and assertion goes here
    })
  })
})
----

[TIP]
====
The `describe(__filename, ...)` makes the test runner print out the path to the test file, which can come in handy when debugging failing tests.
====

`describe(...)` is used to provide some structure to your test suite -- it allows you to structure your test cases to better describe the logical code structure.

`it(...)` is used to cover a single test case.
